---
#- name: "[Darwin] Include vars from Darwin.yml only if configuring system sshd (not from homebrew)"
- name: "[Darwin] Include vars from Darwin.yml"
  include_vars: Darwin.yml
#  when: not sshd_from_homebrew
  tags:
    - sshd

- name: "[Darwin] Include tasks from hombrew.yml only if configuring sshd from homebrew (overwrites some vars from Darwin.yml)"
  include_tasks: homebrew.yml
  when: sshd_from_homebrew
  tags:
    - sshd

# Make sure MacOS uses the correct port for SSH:
- name: "[Darwin] Modify ssh.plist: <SockServiceName> key statement setting port to {{ sshd_port }}"
  replace:
    path: /System/Library/LaunchDaemons/ssh.plist
    regexp: '^(.*<key>SockServiceName</key>\n.*)<string>.*</string>'
    replace: '\1<string>{{ sshd_port }}</string>'
  become: yes
  when: sshd_port is defined and sshd_port != 22
  notify: Restart sshd
  tags:
    - sshd

# If using standard port, make ssh.plist look "natural": use 'ssh' port name instead of '22'
- name: "[Darwin] Modify ssh.plist: make <SockServiceName> key statement use 'ssh' port name instead of '22'"
  replace:
    path: /System/Library/LaunchDaemons/ssh.plist
    regexp: '^(.*<key>SockServiceName</key>\n.*)<string>.*</string>'
    replace: '\1<string>ssh</string>'
  become: yes
  when: sshd_port == 22
  notify: Restart sshd
  tags:
    - sshd

- name: "[Darwin] Modify ssh.plist: <Program> key to use system {{ sshd_wrapper_path }}"
  replace:
    path: /System/Library/LaunchDaemons/ssh.plist
    regexp: '^(.*<key>Program</key>\n.*)<string>.*</string>'
    replace: '\1<string>{{ sshd_wrapper_path }}</string>'
  become: yes
  notify: Restart sshd
  tags:
    - sshd

- name: "[Darwin] Modify ssh.plist: <ProgramArguments> key to use {{ sshd_bin_path }}"
  replace:
    path: /System/Library/LaunchDaemons/ssh.plist
    regexp: '^(.*<key>ProgramArguments</key>\n.*<array>\n.*)<string>.*</string>'
    replace: '\1<string>{{ sshd_bin_path }}</string>'
  become: yes
  notify: Restart sshd
  tags:
    - sshd
...
