---
# handlers file for ansible-sshd

# Linux (SysV, systemd), FreeBSD (BSD init)
- name: Restart sshd service
  service: name=sshd state=restarted
  listen: Restart sshd
  become: yes
  when: ansible_os_family != 'Darwin'

# MacOS (launchd)
- name: ATTENTION!
  debug:
    msg:
      - "sshd is an essential service for ansible AND"
      - "launchd does not support sshd.plist reload with one command"
      - "So the sshd was not reloaded in order to apply changes and must be done manually:"
      - "    'launchctl unload -w /System/Library/LaunchDaemons/ssh.plist'"
      - "    'launchctl load -w /System/Library/LaunchDaemons/ssh.plist'"
  listen: Restart sshd
  when: ansible_os_family == 'Darwin'
...
